<?php
    //  Veritabanı ve diğer ayarları bu dosyada saklarız.
    define("DBUser"     , "root");              // veritabanı kullanıcı adı
    define("DBPass"     , "");                  // eritabanı şifresi
    define("DBServer"   , "localhost");         // veritabanı sunucusu
    define("DBName"     , "dboevleri");         // veritabanı adı
    define("DBFile"     , "inc/dboevleri.sql"); // veritabanı kurulum dosyamızın yolu
    define("UPLOADDir"     , "IMGProfil/");     // kullanıcı profil resimlerinin yükleneceği klasör yolu
    define("CamasirSiniri"     , 2);            // öğrencilerin üst üste alabileceği çamaşır randevusu sınırı
?>